version: "3.9"
services:
  nodejs:
    image: "node:${NODEJS_VERSION}"
    env_file:
      - .env
    working_dir: /usr/src/app
    ports:
      - "${NODEJS_PORT}:3000"
    depends_on:
      - mysql
      - mongo
    volumes:
      - "${NODEJS_VOLUMES_FILES}:/usr/src/app"
    environment:
      - "NODE_ENV=${NODEJS_ENV}"
    command: sh -c "npm install && npm run start:dev"
    restart: always

  nginx-backend:
    image: nginx:${NGINX_BACKEND_VERSION}
    ports:
      - "${NGINX_BACKEND_PORT}:80"
      #- "${NGINX_BACKEND_SSL_PORT}:443"
    expose:
      - ${NGINX_BACKEND_PORT}
      - ${NGINX_BACKEND_SSL_PORT}  
    volumes:
      - "${NGINX_BACKEND_VOLUMES_NGINX_CONF}:/etc/nginx/nginx.conf"
      #- "${NGINX_BACKEND_VOLUMES_NGINX_SSL_CERTS}:/etc/nginx/certs"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - nodejs
    restart: always

  nginx-frontend:
    image: nginx:${NGINX_FRONTEND_VERSION}
    ports:
      - "${NGINX_FRONTEND_PORT}:80"
      #- "${NGINX_FRONTEND_SSL_PORT}:443"
    expose:
      - ${NGINX_FRONTEND_PORT}
      - ${NGINX_FRONTEND_SSL_PORT}  
    volumes:
      - "${NGINX_FRONTEND_VOLUMES_NGINX_CONF}:/etc/nginx/nginx.conf"
      - "${NGINX_FRONTEND_VOLUMES_FILES}:/usr/share/nginx/html"
      #- "${NGINX_FRONTEND_VOLUMES_NGINX_SSL_CERTS}:/etc/nginx/certs"
    command: ["nginx", "-g", "daemon off;"]
    restart: always  

  mysql:
    image: mysql:${MYSQL_VERSION}
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - ${MYSQL_PORT}
    volumes:
      - api-mysql:/var/lib/mysql
    restart: always

  mongo:
    image: mongo:${MONGO_VERSION}
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    expose:
      - ${MONGO_PORT}
    volumes:
      - api-mongo:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    restart: always

volumes:
  api-mysql:
  api-mongo:
